
language_confirm_btn='//*[@id="gatsby-focus-wrapper"]/div[1]/div[2]/div[3]/a'
Help_open='//*[@id="launcher"]'
Help_small_iframe='//*[@id="webWidget"]'
Help_small='//*[(@class="sc-bwzfXH hDrfMZ") and contains(@theme, "[object Object]")]'
Account_type_menu_open='//*[contains(@class, "jss34 jss37")]'
Account_type_menu_personal='//*[contains(@class, "jss41 jss44") and contains(@data-testid, "entity0")]'
Account_type_menu_business='//*[contains(@class, "jss41 jss44") and contains(@data-testid, "entity1")]'
Country_menu_open='//*[contains(@class, "MuiBox-root jss61 jss32 jss59")]'
Country_menu_china='//*[contains(@class, "jss41 jss63") and (@data-testid="country1")]'
Country_menu_vietnam='//*[contains(@class, "jss41 jss63") and (@data-testid="country3")]'
Country_menu_taiwan='//*[contains(@class, "jss41 jss63") and (@data-testid="country6")]'
Title_open='//*[contains(@class, "MuiBox-root jss71 jss32 jss69")]'
Title_Dr='//*[contains(@class, "jss41 jss73") and (@data-testid="title3")]'
First_Name_Input_Text_Field='//*[contains(@class, "jss77 jss81")]'
Middle_Name_Input_Text_Field='//*[contains(@class, "jss77 jss87")]'
Last_Name_Input_Text_Field='//*[contains(@class, "jss77 jss93")]'
Email_Input_Text_Field='//*[contains(@class, "jss77 jss99") and (@data-testid="email")]'
Phone_menu_open='//*[contains(@class, "jss34 jss123")]'
Phone_menu_taiwan='//*[contains(@class, "jss41 jss126") and (@data-testid="undefined1")]'
Phone_Input_Text_Field='//*[contains(@class, "jss77 jss130")]'
Get_verify_code='//*[contains(@class, "jss136 jss137")]'
Verify_code_Input_Text_Field='//*[contains(@class, "jss77 jss145")]'
Next_First_Page='//*[contains(@class, "jss153 jss154")]'
Close='//*[contains(@class, "jss152")]'
Gender_open='//*[contains(@class, "jss34 jss187")]'
Gender_male='//*[contains(@class, "jss41 jss190") and (@data-testid="gender0")]'
Birthday_day_open='//*[contains(@class, "jss34 jss201")]'
Birthday_day_5='//*[contains(@class, "jss41 jss204") and (@data-testid="birthday4")]'
Birthday_month_open='//*[contains(@class, "jss34 jss211")]'
Birthday_month_5='//*[contains(@class, "jss41 jss214") and (@data-testid="birthmonth4")]'
Birthday_year_open='//*[contains(@class, "jss34 jss221")]'
Birthday_year_1998='//*[contains(@class, "jss41 jss224") and (@data-testid="birthyear4")]'
ID_Input_Text_Field='//*[contains(@class, "jss77 jss227")]'
Loc_Input_Text_Field='//*[contains(@class, "jss77 jss233")]'
City_Input_Text_Field='//*[contains(@class, "jss77 jss239")]'
Province_Input_Text_Field='//*[contains(@class, "jss77 jss245")]'
Num_Input_Text_Field='//*[contains(@class, "jss77 jss251")]'
Next_Second_Page='//*[contains(@class, "jss153 jss264")]'
Employment_open='//*[contains(@class, "jss34 jss274")]'
Employment_Employed='//*[contains(@class, "jss41 jss277") and (@data-testid="employment0")]'
Occupation_open='//*[contains(@class, "jss34 jss284")]'
Occupation_Managers='//*[contains(@class, "jss41 jss287") and (@data-testid="occupation0")]'
Industry_open='//*[contains(@class, "jss34 jss294")]'
Industry_Mining='//*[contains(@class, "jss41 jss297") and (@data-testid="industry1")]'
Annual_Income_open='//*[contains(@class, "jss34 jss304")]'
Annual_Income_29999='//*[contains(@class, "jss41 jss307") and (@data-testid="annualIncome0")]'
Total_amount_of_investment_open='//*[contains(@class, "jss34 jss314")]'
Total_amount_of_investment_25000='//*[contains(@class, "jss41 jss317") and (@data-testid="totalInvestmentsSavings0")]'
Trading_Platform_open='//*[contains(@class, "jss34 jss324")]'
Trading_Platform_MetaTrader4='//*[contains(@class, "jss41 jss327") and (@data-testid="platform0")]'
Funding_Currency_open='//*[contains(@class, "jss34 jss334")]'
Funding_Currency_USD='//*[contains(@class, "jss41 jss337") and (@data-testid="fundingCurrency0")]'
Account_Types_open='//*[contains(@class, "jss34 jss344")]'
Account_Types_STANDARD='//*[contains(@class, "jss41 jss347") and (@data-testid="accountType0")]'
Leverage_open='//*[contains(@class, "jss34 jss354")]'
Leverage_150='//*[contains(@class, "jss41 jss357") and (@data-testid="leverage0")]'
Next_Third_Page='//*[contains(@class, "jss153 jss360")]'
P4_Q1='//*[contains(@class, "jss413") and (@type="radio") and (@name="0") and (@value="0")]'
P4_Q2='//*[contains(@class, "jss413") and (@type="radio") and (@name="1") and (@value="0")]'
P4_Q3='//*[contains(@class, "jss413") and (@type="radio") and (@name="2") and (@value="0")]'
P4_Q4='//*[contains(@class, "jss413") and (@type="radio") and (@name="3") and (@value="0")]'
P4_Q5='//*[contains(@class, "jss413") and (@type="radio") and (@name="4") and (@value="0")]'
Next_Four_Page1='//*[contains(@class, "jss422") and (@data-testid="goNext")]'
P4_Q6='//*[contains(@class, "jss413") and (@type="radio") and (@name="5") and (@value="0")]'
P4_Q7='//*[contains(@class, "jss413") and (@type="radio") and (@name="6") and (@value="0")]'
P4_Q8='//*[contains(@class, "jss413") and (@type="radio") and (@name="7") and (@value="0")]'
P4_Q9='//*[contains(@class, "jss413") and (@type="radio") and (@name="8") and (@value="0")]'
P4_Q10='//*[contains(@class, "jss413") and (@type="radio") and (@name="9") and (@value="0")]'
Next_Four_Page2='//*[contains(@class, "jss430 jss431") and (@data-testid="submitExperiences")]'
P5_Terms_Check_0='//*[contains(@class, "jss413") and (@data-testid="terms0")]'
P5_Terms_Check_1='//*[contains(@class, "jss413") and (@data-testid="terms1")]'
P5_Terms_Check_2='//*[contains(@class, "jss413") and (@data-testid="terms2")]'
Next_Five_Page2='//*[contains(@class, "jss430 jss442") and (@data-testid="submitTerms")]'
P6_upload_1='//*[contains(@class, "jss29") and (@type="file") and (@name="pid") and (@data-testid="pid") and (@id="pid")]'
P6_upload_2='//*[contains(@class, "jss29") and (@type="file") and (@name="poa") and (@data-testid="poa") and (@id="poa")]'
P6_upload_3='//*[contains(@class, "jss29") and (@type="file") and (@name="extend1") and (@data-testid="extend1") and (@id="extend1")]'
P6_upload_4='//*[contains(@class, "jss29") and (@type="file") and (@name="extend2") and (@data-testid="extend2") and (@id="extend2")]'
Next_Six_Page='//*[contains(@class, "jss49 jss50") and (@data-testid="submitconfirmIdPersonal")]'
Finish_message='//*[contains(@class, "jss53")]'